# Project: Make Sense of Census

# Data Reading
In this first task, we will load the data to a numpy array and add a new record to it.

Instructions :
The path to the data set has been stored in the variable named path
Load the dataset and store it in a variable called data using np.genfromtxt()
   Example of genfromtxt function
data_file='file.csv' # path for the file
data=np.genfromtxt(data_file, delimiter=",", skip_header=1)

print("\nData: \n\n", data)

print("\nType of data: \n\n", type(data))
Output

Data: 

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]

Type of data: 

 <class 'numpy.ndarray'>
Note:

The parameter 'delimiter="," ' is set because the file that we are opening has extension CSV(Comma Separated Values)

The parameter 'skip_header=1' is set because the first row of the data(which is called header) contains string values but in our numpy array we need only integers(Remember numpy array can only store data of a single data type)

Append 'new_record' (given) to 'data' using "np.concatenate()" and store the new array in a variable called census


In [1]:
# Import Packages/Modules

import numpy as np

In [2]:
# Set the Path for Data:

path = "c:/users/kruti karia/desktop/census.csv"

In [7]:
# Read the Data:

data = np.genfromtxt(path,delimiter=',',skip_header=1)


In [8]:
# Given Additional data:

new_record=[[50,  9,  4,  1,  0,  0, 40,  0]]


In [11]:
# Append the new data:

census = np.concatenate((data,new_record),axis=0)
print(census)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]
 [50.  9.  4. ...  0. 40.  0.]]


In [12]:
# Check the shape:

print(census.shape)

(1001, 8)


# Young Country? Old Country?
We often associate the potential of a country based on the age distribution of the people residing there. We too want to do a simple analysis of the age distribution

Instructions :
Create a new array called 'age' by taking only age column(age is the column with index 0) of 'census' array.

Find the max age and store it in a variable called 'max_age'.

Find the min age and store it in a variable called 'min_age'.

Find the mean of the age and store it in a variable called 'age_mean'.

Find the standard deviation of the age and store it in a variable called 'age_std'.

Ponder whether based on the above statistics, would you classify the country as 'young' or 'old'?


In [13]:
# Create a new array:

age = census[:,0]
print(age)

[39. 50. 38. ... 40. 39. 50.]


In [14]:
# Calculate max age:

max_age = np.max(age)
print(max_age)

90.0


In [15]:
# Calculate min age:

min_age = np.min(age)
print(min_age)

17.0


In [16]:
# Calculate Mean of age:

age_mean = np.mean(age)
print(age_mean)

38.06293706293706


In [17]:
# Calculate Std Deviation of age:

age_std = np.std(age)
print(age_std)

13.341478176165857


# Minority Report
The constitution of the country tries it's best to ensure that people of all races are able to live harmoniously. Let's check the country's race distribution to identify the minorities so that the government can help them.

Instructions :
Create four different arrays by subsetting 'census' array by Race column(Race is the column with index 2) and save them in 'race_0','race_1', 'race_2', 'race_3' and 'race_4' respectively(Meaning: Store the array where 'race'column has value 0 in 'race_0', so on and so forth)

Store the length of the above created arrays in 'len_0', 'len_1','len_2', 'len_3' and 'len_4' respectively

Find out which is the race with the minimum no. of citizens

Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )



In [20]:
#Creating new subsets based on 'Age'

race_0 = census[census[:,2]==0]

race_1 = census[census[:,2]==1]

race_2 = census[census[:,2]==2]

race_3 = census[census[:,2]==3]

race_4 = census[census[:,2]==4]

In [21]:
#Finding the length of the above created subsets

len_0 = len(race_0)

len_1 = len(race_1)

len_2 = len(race_2)

len_3 = len(race_3)

len_4 = len(race_4)

In [22]:
#Printing the length of the above created subsets

print(len_0)
print(len_1)
print(len_2)
print(len_3)
print(len_4)

10
27
110
6
848


In [23]:
#Storing the different race lengths with appropriate indexes
race_list=[len_0, len_1,len_2, len_3, len_4]
print(race_list)

[10, 27, 110, 6, 848]


In [27]:
#Storing the race with minimum length into a variable 

minority_race = race_list.index(min(race_list))
minority_race

3

# Senior Welfare
As per the new govt. policy, all citizens above age 60 should not be made to work more than 25 hours per week. Let us look at the data and see if that policy is followed.

Instructions:
Create a new subset array called 'senior_citizens' by filtering 'census' according to age>60 (age is the column with index 0)

Add all the working hours(working hours is the column with index 6) of 'senior_citizens' and store it in a variable called 'working_hours_sum'

Find the length of 'senior_citizens' and store it in a variable called 'senior_citizens_len'

Finally find the average working hours of the senior citizens by dividing 'working_hours_sum' by 'senior_citizens_len' and store it in a variable called 'avg_working hours'.

Print 'avg_working_hours' and see if the govt. policy is followed.



In [28]:
#Subsetting the array based on the age 

senior_citizens = census[census[:,0]>60]

In [34]:
#Calculating the sum of all the values of array

working_hours_sum = senior_citizens.sum(axis=0)[6]
print(working_hours_sum)

1917.0


In [35]:
#Finding the length of the array

senior_citizens_len = len(senior_citizens)
print(senior_citizens_len)

61


In [36]:
#Finding the average working hours

avg_working_hours = working_hours_sum/senior_citizens_len
print(avg_working_hours)

31.42622950819672


# Education Matters!
Our parents have repeatedly told us that we need to study well in order to get a good(read: higher-paying) job. Let's see whether the higher educated people have better pay in general.

Instructions :
Create two new subset arrays called 'high' and 'low' by filtering 'census' according to education-num>10 and education-num<=10 (education-num is the column with index 1) respectively.
Find the mean of income column(income is the column with index 7) of 'high' array and store it in 'avg_pay_high'. Do the same for 'low' array and store it's mean in 'avg_pay_low'.
Note: - Since income is a binary variable, mean() here represents the percentage of ppl having annual income higher than 50K. - You could have used "mean()" function to solve the task 'Young Country? Old Country?' as well.

Compare 'avg_pay_high' and 'avg_pay_low' and see whether there is truth in better education leads to better pay


In [38]:
#Creating an array based on 'education' column

high = census[census[:,1]>10]

low = census[census[:,1]<=10]

In [40]:
#Finding the average pay

avg_pay_high = high[:,7].mean()

avg_pay_low = low[:,7].mean()

print(avg_pay_high)

print(avg_pay_low)

0.42813455657492355
0.13649851632047477
